name: Exploits
description: Fight common exploits
author: StarTux
version: 0.1
main: com.winthier.exploits.bukkit.BukkitExploitsPlugin
database: true
depend: []
commands:
  exploits:
    description: Admin interface
    permission: exploits.exploits
    usage: /<command>
permissions:
  exploits.exploits:
    description: Use the /exploits command
    default: op
